name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: checkout
      uses: actions/checkout@v3
      with:
        token: ${{ steps.generate_token.outputs.token }}

    - name: tagpr
      uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}